# Generated by Django 3.0 on 2020-02-26 18:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=10)),
                ('relation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('total_duration', models.IntegerField()),
                ('duration_per_class', models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(30)])),
                ('chapters', models.ManyToManyField(to='classroomapp.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30)),
                ('doj', models.DateField()),
                ('salary', models.FloatField()),
                ('web_lecture', models.BooleanField(default=False)),
                ('subjects', models.ManyToManyField(to='classroomapp.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('doj', models.DateField()),
                ('standard', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('roll_no', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('point_of_contact', models.ManyToManyField(to='classroomapp.PointOfContact')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seating_capacity', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(15)])),
                ('web_lecture_support', models.BooleanField(default=False)),
                ('shape', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroomapp.ClassroomShape')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomapp.Classroom')),
                ('students', models.ManyToManyField(to='classroomapp.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomapp.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomapp.Teacher')),
            ],
        ),
    ]
