# Generated by Django 3.0 on 2020-02-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomshape',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
